version: '3.8'

services:
  frontend:
    build:
      context: ../frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_BACKEND_URL=http://backend:8000
    volumes:
      - ../frontend:/app
      - /app/node_modules
    depends_on:
      - backend

  backend:
    build:
      context: ../backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/efiko
      - REDIS_URL=redis://redis:6379
      - FIREBASE_ADMIN_CREDENTIAL=${FIREBASE_ADMIN_CREDENTIAL}
    volumes:
      - ../backend:/app
    depends_on:
      - db
      - redis

  db:
    image: postgres:14-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=efiko
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  vector_store:
    build:
      context: ../vector_db
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/efiko
      - REDIS_URL=redis://redis:6379
    volumes:
      - ../vector_db:/app
      - vector_store_data:/app/vector_store
    depends_on:
      - db
      - redis

volumes:
  postgres_data:
  redis_data:
  vector_store_data:
